-- 코드를 입력하세요
# 평균 대여 기간이 7일 이상인 자동차들 id와 평균 대여 기간리스트 출력 => 소수 두번째자리에서 반올림
# 주의 : 시작한 날짜부터 세야하기 때문에 시작한 날짜 +1 해야함
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;